### ISSUE TITLE
DOES NOT WORK ON VERSION 1.21

### ISSUE THREAD

**Issue by PegasovFly** [murphy-slaw/worse-swimming#1]
[16:51:34] [main/INFO]: Fix: add [], remove [], replace [[worse-swimming 1.0.0-1.21] -> add:worse-swimming 1 ([(-тИЮ,тИЮ)])]
[16:51:34] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
         - Replace mod 'Worse Swimming' (worse-swimming) 1.0.0-1.21 with any version that is compatible with:
                 - minecraft 1.21
More details:
         - Mod 'Worse Swimming' (worse-swimming) 1.0.0-1.21 requires any version between 1.20.1 (inclusive) and 1.21- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]

**Comment by ZiLenTz** [comment]
Same here. Somehow it doesn't work with MC 1.21.

`Replace mod 'Worse Swimming' (worse-swimming) 1.0.0-1.21 with any version that is compatible with: minecraft 1.21`

**Comment by murphy-slaw** [comment]
Ugh. The mod metadata had the wrong version. Fixed.

New build posted to modrinth as 
https://modrinth.com/mod/worse-swimming/version/1.0.0-1.21-1
